spring:
  application:
    name: course-management
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:courseapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: never
server:
  error:
    include-stacktrace: NEVER
  servlet:
    session:
      cookie:
        same-site: strict
        http-only: true
app:
  plugin:
    url:
logging:
  level:
    ru.mtuci.coursemanagement.config.SecurityAuditLogger: WARN
  file:
    name: security-audit.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"